# -*- coding: utf-8 -*-
"""BIU 003 Data Cleansing - Z Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/119bQ49ozHg-qlAOoj7Fgn1U__L9A4_cq

# Outliers
Z-Score
Memmal Sleep dataset
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

animals = pd.read_csv(r"C:\Users\ophir\OneDrive\Desktop\mammalsleep.csv")
animals = animals.iloc[:,1:12]
animals.head()

animals.shape

"""<u>Mammal Sleep Dataset</u>

<table>
    <tr><th>species</th><td>Species of animal</td></tr>
    <tr><th>bw</th><td> Body weight (kg)</td></tr>
    <tr><th>brw</th><td> Brain weight (g)</td></tr>
    <tr><th>sws</th><td> Slow wave ("nondreaming") sleep (hrs/day)</td></tr>
    <tr><th>ps</th><td> Paradoxical ("dreaming") sleep (hrs/day)</td></tr>
    <tr><th>ts</th><td> Total sleep (hrs/day) (sum of slow wave and paradoxical sleep)</td></tr>
    <tr><th>mls</th><td> Maximum life span (years)</td></tr>
    <tr><th>gt</th><td> Gestation time (days)</td></tr>
    <tr><th>pi</th><td> Predation index (1-5), 1 = least likely to be preyed upon</td></tr>
    <tr><th>sei</th><td> Sleep exposure index (1-5), 1 = least exposed (e.g. animal sleeps in a well-protected den), 5 = most exposed</td></tr>
    <tr><th>odi</th><td> Overall danger index (1-5) based on the above two indices and other information, 1 = least danger (from other animals), 5 = most danger (from other animals)</td></tr>
</table>

"""

animals.info()

animals.describe()

"""# Outlier Detection

### Graphical methods

Creating data set of continuese data
"""

#Continues Numeric Columns
cols= ['bw','brw','sws','ps','ts','mls','gt']
con_df = animals[cols]

## Using box (Wiskers) plot
plt.figure(figsize=(20,200))

def outliers_boxplot(animals):
    for i, col in enumerate(animals.columns):

            ax = plt.subplot(60, 3, i+1)
            sns.boxplot(data=animals, x=col, ax=ax)
            plt.subplots_adjust(hspace = 0.7)
            plt.title('Box Plot: {}'.format(col), fontsize=15)
            plt.xlabel('{}'.format(col), fontsize=14)

outliers_boxplot(con_df)

"""## Using Mathematical Functions

### Z-Score
"""

# Importing scipy stats and zscore libreries
from scipy import stats
from scipy.stats import zscore

"""Mammals' Body Weight"""

#Results using z-score
z = np.abs(stats.zscore(animals.bw))
print(z)

###  using scatterplots
sns.scatterplot(x=animals.index,y=animals['bw'])

"""Mammals' Brain Weight"""

sns.scatterplot(x=animals.index,y=animals['brw'])

## Eliminating those points
animals2 = animals.copy()
#2.5 Standart Diviatin from CT
threshold = 2.5
animals2 = animals2[(z < threshold)]

sns.scatterplot(x=animals2.index,y=animals2['bw'])

"""Ex. <br>
1. Calculate z-scores for the 'brw' column to identify outliers<br>
2. Return the rows where 'brw' outliers appear
"""

###  using scatterplots
sns.scatterplot(x=animals.index,y=animals['brw'])

## Eliminating those points
animals3 = animals.copy()
#2.5 Standart Diviatin from CT
threshold = 3
animals3 = animals2[(z < threshold)]

sns.scatterplot(x=animals3.index,y=animals3['brw'])

animals3['brw']

# Assuming animals3 is your DataFrame
animals3['brw_zscore'] = zscore(animals3['brw'])

animals3['brw_zscore']

"""### Ouliers with Z-Score /SD"""

# Step 1: Calculate z-scores per cell
z_scores = (con_df - con_df.mean()) / con_df.std()

# Step 2: Replace only outlier cells (|z| > 2.5 or 3) with NaN
clean_df = con_df.mask(z_scores.abs() > 3)

print("Original shape:", con_df.shape)
print("Cleaned shape:", clean_df.shape)
clean_df.head()

