# -*- coding: utf-8 -*-
"""Data Cleansing Missing Values - lesson 003.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGQAtw5OKPTt-9DsLkkQn09rw6Kjwxud

# Missing Values
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
# %matplotlib inline
import warnings
warnings.filterwarnings("ignore")

"""Creating Random Dataset"""

# Creating the DataFrame
data = {
    'A': [17, 18, 10, 17, 17, 11, 18, 19, 10, 10, 14, 15, 16, 15, 18, 13, 14, 14, 12, 10],
    'B': [16, 18, 17, 17, 12, 17, 19, 11, 19, 12, 13, 19, 16, 13, 19, 15, 13, 14, 10, 11],
    'C': [17, 13, 10, 11, 12, 14, 12, 15, 12, 11, 14, 19, 11, 19, 14, 16, 11, 12, 19, 18]
}

df = pd.DataFrame(data)

# Introducing random nulls
np.random.seed(42)  # For reproducibility
for col in df.columns:
    df.loc[df.sample(frac=0.2).index, col] = np.nan  # 20% nulls in each column

df

df.shape

df.info()

df.A

"""Filling Nulls"""

# df.A.fillna(200)
df.A.fillna({0:2000,1:3000})

#Column B
#Mean
print(df.B.mean())
#Standard Deviation
print(df.B.std())

#pd.Series(np.random.normal(mean,Standard Deviation,100))
#'5' =15.31
#'3.15': The standard deviation, which controls the spread or dispersion of the distribution
#'100': The number of random numbers to generate.
s1 = pd.Series(np.random.normal(5,10,50))
df['B'].fillna(s1,inplace=True)

df['B']

#forward-fill method
print(df.A)

print(df.A.fillna(method='ffill'))

df.C

# linear interpolation
df.C.interpolate()